### ISSUE TITLE
Cmd+Period support

### ISSUE THREAD

**Issue by lnihlen** [ScintillatorSynth/Scintillator#130]
The audio synth server respects the cmd+. command, halting the running synths. Worth considering adding this support to Scintillator too.

**Comment by mossheim** [comment]
FYI for SuperCollider it's the language client that does this, not the server. i would not recommend implementing this shortcut directly in Scintillator, and rather use the CmdPeriod class in your sclang code (http://doc.sccode.org/Classes/CmdPeriod.html)
