### ISSUE TITLE
Rename all Scintillator sclang classes to have a consistent "Scin" prefix

### ISSUE THREAD

**Issue by dyfer** [ScintillatorSynth/Scintillator#139]
Hello,
I have encountered two quarks that both use a class called `Sampler`. TL;DR installing both quarks results in a duplicate class and prevents SC class library from compiling.

While there's no policy about naming classes in Quarks and duplicates are possible/unavoidable, I'd like to submit this information to possibly encourage the use of more specific class names in each respective quark.
I'm submitting this information for both quarks. I understand that solving this might not be possible, but I thought I'd raise awareness about this. The two quarks are:
- [Scintillator](https://github.com/ScintillatorSynth/Scintillator)
- [SuperSampler](https://github.com/allenloves/SuperSampler)

**Comment by lnihlen** [comment]
Hey dyfer, thanks for bringing this to my attention. I can rename my Sampler class to make it clear it is an ImageSampler. (new name TBD)

**Comment by lnihlen** [comment]
Based on some additional discussion, co-opting this bug to make it a task to rename all Scintillator sclang classes with a consistent Scin prefix.

**Comment by lnihlen** [comment]
Naming convention is now that all VGens start with `V` prefix, and all other Scintillator classes start with a `Scin` prefix. So `Sampler` has been renamed in 0.0.7 to `VSampler`. Hoping this will improve clarity (and interoperability) of the Scintillator Quark. If there are other name conflicts that arise please do let me know, as Scintillator is in alpha state right now the API is still pretty plastic!
