### ISSUE TITLE
unable to boot server first time on scnvim

### ISSUE THREAD

**Issue by cdbzb** [ScintillatorSynth/Scintillator#144]
scin installer detects version match 0.0.6 between Quark and binary.
*** You're all set, happy Scintillating!
~v=ScinServer.new.boot;

->a ScinServer
ERROR: unknown command line flag 'crashpadHandlerPath'
RESULT = 1
*** scinsynth fatal error, code: 1

**Comment by lnihlen** [comment]
Hey, thanks for reporting. This is now a known issue which is that I didn't understand Quark versioning, and the production binary has gotten way out of sync with the production sclang code. I'm sprinting to release v0.0.7, to repair. This should be out in the next day or so. Sorry about the problem, hoping to have a fix soon!

**Comment by cdbzb** [comment]
awesome excited to get started thx!

**Comment by lnihlen** [comment]
Hey, I've released v0.0.7. Lots of stuff updated, see the [release notes](https://scintillatorsynth.org/docs/developer-documentation/scintillator-release-notes/) for more info. I'm moving to a different release process after this, so hopefully subsequent development won't break this release. Please do give it another try, thanks!

**Comment by cdbzb** [comment]
Yay excited to try it out...

**Comment by lnihlen** [comment]
Assuming this was fixed in the 0.0.7 release. If not please do re-open, or file another bug. Thanks for trying Scintillator!
