### ISSUE TITLE
ScinServerStatusPoller stuck in booting stage

### ISSUE THREAD

**Issue by nhthn** [ScintillatorSynth/Scintillator#172]
**Background:** Instantiating Scinths gives me a "Message 'server' not understood, receiver nil" error. I did some digging and found that the root cause is ScinServerStatusPoller being stuck in a booting stage even though the server is up and running. Luckily it's a purely class library side issue, scinsynth is working fine.

**Minimal reproducer:**

```
OSCFunc.trace;
ScinServer.default.options.swiftshader = true; // probably not relevant
ScinServer.default.doWhenBooted({
    "Hello world".postln;
});
ScinServer.default.boot;
```

**Expected behavior:** a blank Scintillator server window appears, /scin_server.reply messages are sent to sclang, "Hello world" is printed to the post window.

**Actual behavior:** a blank Scintillator server window appears, /scin_server.reply message are sent to sclang, but no "Hello world" is posted.

**Investigation:** It seems that the ScinServerStatusPoller's OSCFunc/SkipJack are being instantiated "too early" somehow. The default server is instantiated right as sclang is booting up, so I suspect there maybe some weird race condition in sclang as it wakes up.

To test this I moved the creation of ScinServerStatusPoller to the beginning of `ScinServer:boot` instead of `ScinServer:init`. It's a quick bandage (and breaks ScinServer:doWhenBooted since the poller is initially nil) but with that patch I can create Scinths, and the examples from the guide run successfully.

I'm guessing a proper fix is to make the initial state of ScinServerStatusPoller dormant, and not start the OSCFunc/SkipJack until we've booted the server and it's necessary to monitor OSC messages. This is closer to how ServerStatusWatcher works (and will also catch the case where Cmd+. is run between booting the interpreter and booting the server, which kills the OSCFunc).

I'll likely have time to file a PR to fix this within the next week

**Comment by lnihlen** [comment]
Ooh, good catch. I have yet to find a means of osc communication in sclang that isn't full of races. I'd welcome a PR, or can take a look myself if you get busy with other stuff.
